import { ClerkProvider } from "@clerk/nextjs";
import "~/styles/globals.css";
import { TopNav } from "./_components/topNav";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "T3 Stack Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html>
        <body className={'font-sans ${inter.variable} flex flex-col gap-4'}>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>    
  );
}
